service: piertutor

image: edoardodep/piertutor

servers:
  web:
    - 188.245.178.80

proxy:
  ssl: true
  hosts:
    - piertutor.com
    - www.piertutor.com

registry:
  username: edoardodep
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - SECRET_KEY_BASE
    - MAILGUN_SMTP_USERNAME
    - MAILGUN_SMTP_PASSWORD
  clear:
    SOLID_QUEUE_IN_PUMA: true

volumes:
  - "piertutor-storage:/rails/storage"
  - "piertutor-database:/rails/storage/*.sqlite3"

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

asset_path: /rails/public/assets

builder:
  arch: arm64

ssh:
  user: root